---
- name: Install packages with Chocolatey
  hosts: windows
  gather_facts: false
  vars:
    choco_packages:
      - name: 7zip
      - name: azcopy10
      - name: microsoftazurestorageexplorer
      - name: sql-server-management-studio
      
  tasks:
    - name: Install Chocolatey packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: present
      loop: "{{ choco_packages }}"